AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'bin/**/*'
    - 'db/**/*.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'log/**/*'

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-minitest

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: never

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - config/routes.rb
